// ── 自定义 CSS 快捷预设 ──
const CSS_PRESETS = [
    {
        name: '晨曦金',
        css: '/* 晨曦金 — 暖黄米色，柔和明亮 */\n:root {\n  --primary-color: #d4920a;\n  --primary-dark: #b07708;\n  --bg-color: #fef9ef;\n  --panel-color: #ffffff;\n  --dark: #5c4200;\n  --gray: #8b7355;\n  --border: #f0e0b8;\n  --shadow: 0 4px 20px rgba(180,140,20,0.1);\n  --header-bg: #fdf5e6;\n}\n\n/* 按钮：纯色无渐变 */\n.toggle-mode-btn,\n.float-toggle-btn {\n  background: var(--primary-color);\n}\n.toggle-mode-btn:hover,\n.float-toggle-btn:hover {\n  background: var(--primary-dark);\n}\n\n#display {\n  border-radius: 18px;\n  background: #fffdf5;\n  border: 1px solid #f0d78c;\n}\n\n.control-btn { border-radius: 10px; border-color: #e8d5a0; }\n.control-btn:hover { background: #fff8e1; box-shadow: 0 2px 8px rgba(200,150,20,0.2); }\n\n.settings-header { background: #fdf5e6; }\n.settings-nav { background: #fef9ef; }\n.saved-lists-container { background: var(--panel-color); border-color: var(--border); }\n.saved-list-header { background: #fdf5e6; border-bottom-color: var(--border); }\n.saved-list-item { background: var(--panel-color); }\n.saved-list-item:hover { background: #fef9ef; }\n.saved-list-wrapper.current-using .saved-list-item { background: #fef6e8; }\n.list-detail-panel { background: #fefaf3; }\n.mq-toast-card { background: var(--panel-color); }\n.mode-card { background: var(--panel-color); border-color: var(--border); }\n'
    },
    {
        name: '薄荷冰',
        css: '/* 薄荷冰 — 青绿清爽，干净利落 */\n:root {\n  --primary-color: #00a878;\n  --primary-dark: #008e65;\n  --bg-color: #f0fdf9;\n  --panel-color: #ffffff;\n  --dark: #1a3c34;\n  --gray: #5d8a7c;\n  --border: #c8f0e5;\n  --shadow: 0 4px 16px rgba(0,168,120,0.08);\n  --header-bg: #eafaf4;\n}\n\n/* 按钮：纯色无渐变 */\n.toggle-mode-btn,\n.float-toggle-btn {\n  background: var(--primary-color);\n}\n.toggle-mode-btn:hover,\n.float-toggle-btn:hover {\n  background: var(--primary-dark);\n}\n\n#display {\n  border-radius: 16px;\n  background: #fafffd;\n  border: 1px solid #c8f0e5;\n}\n\n.control-btn { border-radius: 8px; border-color: #c8f0e5; }\n.control-btn:hover { background: #e6faf4; transform: translateY(-1px); box-shadow: 0 4px 12px rgba(0,168,120,0.15); }\n\n.settings-header { background: #eafaf4; }\n.settings-nav { background: #f4fdf9; }\n.saved-lists-container { background: var(--panel-color); border-color: var(--border); }\n.saved-list-header { background: #eafaf4; border-bottom-color: var(--border); }\n.saved-list-item { background: var(--panel-color); }\n.saved-list-item:hover { background: #f4fdf9; }\n.saved-list-wrapper.current-using .saved-list-item { background: #eafaf4; }\n.list-detail-panel { background: #f6fdfa; }\n.mq-toast-card { background: var(--panel-color); }\n.mode-card { background: var(--panel-color); border-color: var(--border); }\n'
    },
    {
        name: '深海蓝',
        css: '/* 深海蓝 — 开阔宁静，蓝色清爽 */\n:root {\n  --primary-color: #0984e3;\n  --primary-dark: #0767b3;\n  --bg-color: #e8f4fd;\n  --panel-color: #ffffff;\n  --dark: #0a3d62;\n  --gray: #5a8aaa;\n  --border: #c8e2f8;\n  --shadow: 0 4px 18px rgba(9,132,227,0.08);\n  --header-bg: #e2f0fb;\n}\n\n/* 按钮：纯色无渐变 */\n.toggle-mode-btn,\n.float-toggle-btn {\n  background: var(--primary-color);\n}\n.toggle-mode-btn:hover,\n.float-toggle-btn:hover {\n  background: var(--primary-dark);\n}\n\n#display {\n  border-radius: 20px;\n  background: #fafdff;\n  border: 1px solid #d0e8fa;\n  font-size: 3.2em;\n}\n\n.control-btn { border-radius: 22px; border-color: #c8e2f8; }\n.control-btn:hover { background: #e1f0fb; box-shadow: 0 3px 10px rgba(9,132,227,0.18); }\n\n.settings-header { background: #e2f0fb; }\n.settings-nav { background: #f0f7fd; }\n.settings-menu { border-radius: 14px; }\n.saved-lists-container { background: var(--panel-color); border-color: var(--border); }\n.saved-list-header { background: #e2f0fb; border-bottom-color: var(--border); }\n.saved-list-item { background: var(--panel-color); }\n.saved-list-item:hover { background: #f0f7fd; }\n.saved-list-wrapper.current-using .saved-list-item { background: #e8f3fc; }\n.list-detail-panel { background: #f4f9fe; }\n.mq-toast-card { background: var(--panel-color); }\n.mode-card { background: var(--panel-color); border-color: var(--border); }\n'
    },
    {
        name: '薰衣草',
        css: '/* 薰衣草 — 淡紫柔美，衬线字体 */\n@import url(\'https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;600;700&display=swap\');\n\n:root {\n  --primary-color: #7c3aed;\n  --primary-dark: #6d28d9;\n  --bg-color: #f9f7ff;\n  --panel-color: #ffffff;\n  --dark: #3c1f70;\n  --gray: #8a7fb0;\n  --border: #e4dcf8;\n  --shadow: 0 4px 16px rgba(124,58,237,0.08);\n  --header-bg: #f2edfc;\n}\n\nbody {\n  font-family: \'Noto Serif SC\', \'楷体\', \'KaiTi\', serif;\n  letter-spacing: 0.02em;\n}\n\n/* 按钮：纯色无渐变 */\n.toggle-mode-btn,\n.float-toggle-btn {\n  background: var(--primary-color);\n}\n.toggle-mode-btn:hover,\n.float-toggle-btn:hover {\n  background: var(--primary-dark);\n}\n\n#display {\n  border-radius: 20px;\n  background: #fefdff;\n  border: 1px solid #e4dcf8;\n  font-size: 3em;\n  font-weight: 700;\n}\n\n.control-btn { border-radius: 14px; border-color: #e4dcf8; }\n.control-btn:hover { background: #f5f2ff; box-shadow: 0 3px 12px rgba(124,58,237,0.2); }\n\n.settings-header { background: #f2edfc; }\n.settings-nav { background: #f8f5ff; }\n.saved-lists-container { background: var(--panel-color); border-color: var(--border); }\n.saved-list-header { background: #f2edfc; border-bottom-color: var(--border); }\n.saved-list-item { background: var(--panel-color); }\n.saved-list-item:hover { background: #f8f5ff; }\n.saved-list-wrapper.current-using .saved-list-item { background: #f0eafa; }\n.list-detail-panel { background: #faf8ff; }\n.mq-toast-card { background: var(--panel-color); }\n.mode-card { background: var(--panel-color); border-color: var(--border); }\n'
    },
    {
        name: '毛玻璃',
        css: '/* 毛玻璃 — 白色背景 + 半透明模糊面板 */\n:root {\n  --primary-color: #6366f1;\n  --primary-dark: #4f46e5;\n  --bg-color: #f8f8fa;\n  --panel-color: rgba(255,255,255,0.72);\n  --dark: #1e1b4b;\n  --gray: #6b7280;\n  --border: rgba(0,0,0,0.06);\n  --shadow: 0 8px 32px rgba(0,0,0,0.06);\n  --header-bg: rgba(255,255,255,0.5);\n}\n\nbody {\n  background: #f8f8fa !important;\n}\n\n/* 按钮：纯色无渐变 */\n.toggle-mode-btn,\n.float-toggle-btn {\n  background: var(--primary-color);\n}\n.toggle-mode-btn:hover,\n.float-toggle-btn:hover {\n  background: var(--primary-dark);\n}\n\n#display {\n  background: rgba(255,255,255,0.7);\n  backdrop-filter: blur(20px);\n  -webkit-backdrop-filter: blur(20px);\n  border: 1px solid rgba(0,0,0,0.06);\n  border-radius: 20px;\n}\n\n.settings-header { background: rgba(255,255,255,0.5); }\n\n.settings-menu {\n  background: rgba(255,255,255,0.75);\n  backdrop-filter: blur(28px);\n  -webkit-backdrop-filter: blur(28px);\n  border: 1px solid rgba(0,0,0,0.06);\n}\n\n.settings-nav {\n  background: rgba(255,255,255,0.4);\n  border-right: 1px solid rgba(0,0,0,0.05);\n}\n\n.saved-lists-container {\n  background: rgba(255,255,255,0.7);\n  backdrop-filter: blur(16px);\n  -webkit-backdrop-filter: blur(16px);\n  border-color: rgba(0,0,0,0.06);\n}\n\n.saved-list-header { background: rgba(255,255,255,0.4); border-bottom-color: rgba(0,0,0,0.05); }\n.saved-list-item { background: transparent; }\n.saved-list-item:hover { background: rgba(255,255,255,0.5); }\n.saved-list-wrapper.current-using .saved-list-item { background: rgba(99,102,241,0.06); }\n.list-detail-panel { background: rgba(255,255,255,0.3); }\n\n.history-panel {\n  background: rgba(255,255,255,0.7);\n  backdrop-filter: blur(16px);\n  -webkit-backdrop-filter: blur(16px);\n  border: 1px solid rgba(0,0,0,0.06);\n}\n\n.mq-toast-card { background: rgba(255,255,255,0.8); backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px); }\n.mode-card { background: rgba(255,255,255,0.7); border-color: rgba(0,0,0,0.06); }\n\n.control-btn {\n  background: rgba(255,255,255,0.7);\n  backdrop-filter: blur(8px);\n  -webkit-backdrop-filter: blur(8px);\n  border: 1px solid rgba(0,0,0,0.08);\n  border-radius: 10px;\n}\n\n.control-btn:hover {\n  background: rgba(255,255,255,0.9);\n  transform: translateY(-1px);\n  box-shadow: 0 4px 16px rgba(0,0,0,0.08);\n}\n'
    }
];
